const { validateCredential } = require('../src/validator');
const { phoneSchema } = require('../src/schema/phone/phone-schema-v1.js');

const phoneJwt = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NkstUiJ9.eyJpYXQiOjE2MzA0NDU2OTIsInN1YiI6ImRpZDpldGhyOjB4ODRiMmYxYzM0MzE3NmQyNjRhMThlOWRmMGZmZGE4MDM0ZDc3N2ZiNiIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsiUGhvbmUiOnsicHJldmlldyI6eyJ0eXBlIjowLCJmaWVsZHMiOlsicGhvbmVOdW1iZXIiXX0sImNhdGVnb3J5IjoiaWRlbnRpdHkiLCJkYXRhIjp7InBob25lTnVtYmVyIjoiKzU0MjQ5NDYwMzI4NiJ9fX19LCJpc3MiOiJkaWQ6ZXRocjoweDJiMTg0MjAzYmFiZWZlMzA2OTAxYTc2YjA1M2JjMzg2NTllNGE3OTUifQ.xxCd7H-wdSZyO60h7IUZpi4FjhrphZS45N_pRKXsfGSWo5_X_DvMysdaT1ykJRH2UkoEoPFEAAbDi953buLFgwE'
const phoneJwtFail = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzA0NDU2OTIsInN1YiI6ImRpZDpldGhyOjB4ODRiMmYxYzM0MzE3NmQyNjRhMThlOWRmMGZmZGE4MDM0ZDc3N2ZiNiIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiXSwiY3JlZGVudGlhbFN1YmplY3QiOnsiUGhvbmUiOnsicHJldmlldyI6eyJ0eXBlIjoiMCIsImZpZWxkcyI6WyJwaG9uZU51bWJlciJdfSwiY2F0ZWdvcnkiOiJpZGVudGl0eSIsImRhdGEiOnsicGhvbmVOdW1iZXIiOiIrNTQyNDk0NjAzMjg2In19fX0sImlzcyI6ImRpZDpldGhyOjB4MmIxODQyMDNiYWJlZmUzMDY5MDFhNzZiMDUzYmMzODY1OWU0YTc5NSJ9.a4TlMDDkgmQBwh4E0UoA83o_WiaH2dmO1qZIAYDOASE'

test('Validate OK', async () => {
    result = await validateCredential(phoneSchema, phoneJwt);
    expect(result).toBe(true);
});

test('Validate FAIL', async () => {
    result = await validateCredential(phoneSchema, phoneJwtFail);
    expect(result).toBe(false);
});