on: push
name: Ejecutar tests al hacer push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone and checkout'
        uses: actions/checkout@v1
      - name: 'install dependencies'
        run: npm install
      - name: 'run ESlint'
        run: npm run lint
      - name: 'run Eslint:fix'
        run: npm run lint:fix
      - name: 'npm run tests'
        run: npm test
