on: push
name: Ejecutar tests al hacer push
jobs:
  tests:
    runs-on: ubuntu-latest
      - name: "clone and checkout"
        uses: actions/checkout@v1
      - name: "install dependencies"
        run: npm install
      - name: "run ESlint"
        run: npm lint
      - name: "run Eslint:fix"
        run: npm lint:fix
      - name: "run tests"
        run: npm test
